version: '{build}'
branches:
  only:
    - master
    - dev
image: 
  - Visual Studio 2019
  - Ubuntu

build_script:
- ps: |
    if($isWindows){
    ./build.ps1  
    }
- sh: |
    if ($isLinux) {
      ./build.sh  
    }