version: '{build}'
branches:
  only:
    - master
    - dev
image: 
  - Visual Studio 2019
  - Ubuntu

configuration: Release

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

install:
- sh: chmod +x ./build.sh

build_script:
- ps: ./build.ps1
- sh: ./build.sh