version: '{build}'
branches:
  only:
    - master
    - dev
image: 
  - Visual Studio 2019
  - Ubuntu

configuration: Release
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

build_script:
- ps: ./build.ps1
- sh: chmod +x ./build.sh